### ISSUE TITLE
Not a issue - but a question ;-)

### ISSUE THREAD

**Issue by HubertusH** [marcus-j-davies/node-red-semaphore-plus#1]
Hi, a question about the semaphores: if I have several nodes semaphore takes on the same semaphore in one and the same flow - do I have to have just as many release nodes correspondingly or can I combine all releases on one node? Since it is a global release, this should actually work.

Thank you and best regards
Hubertus

**Comment by marcus-j-davies** [comment]
Hi @HubertusH 

As the release works on the global queue - you can use the one release node, it’s really up to you (you can have as many as like - they will all affect the same global queue)

The node does not need to be married.

**Comment by HubertusH** [comment]
Thank you, great. Then the flows will be a bit clearer.
