### ISSUE TITLE
use semaphore in subflow 

### ISSUE THREAD

**Issue by HubertusH** [marcus-j-davies/node-red-semaphore-plus#2]
Semaphores work fine - but if the call of Take and Release happens in a subflow, Nodered gets confused. When deploying changed flows, they are not restarted and the debug nodes can still be enabled/disabled, but the output is not updated.

To check this, simply put take and release in a subflow and restart nodered (node-red-restart) - otherwise you cannot reproduce the problem. 

BR
Hubertus

**Comment by marcus-j-davies** [comment]
Sorry not sure I follow...

This is a standard set of Nodes for Node RED, that uses Config Nodes to orchestrate and manage the queue, 
what has debug nodes got to do with this?

If you mean a queue config  Node created inside of a sub flow,  is not seen by non sub flow nodes - this is standard behaviour in Node RED, a config node needs creating outside of the sub flow to see it outside and in the subflow

**Comment by HubertusH** [comment]
Yes, that's clear.

the configuration takes place/and did take place outside of a subflow. Therefore, this can actually be ruled out.

I have drastically reduced the semaphore calls - at the moment everything works. I'll let you know if I expect problems here again.

Thanks for now and best regards
