### ISSUE TITLE
GQ Limit == 1 leads to two messages being processed

### ISSUE THREAD

**Issue by pshirshov** [marcus-j-davies/node-red-semaphore-plus#3]
I'm trying to build a flow which would reject any messages which arrive while the semaphore is locked.
So, I'm trying to set GQ limit to 1.

When the first message arrives the semaphore locks, the message is being passed further and the queue remains empty.
When the second message arrives, it will be pending in the queue, further messages will be rejected, but the second message will be processed once the semaphore releases.

It seems like I cannot implement the desired logic, am I correct?

**Comment by marcus-j-davies** [comment]
Hi @pshirshov,

The `Avoidance Mode` when set to `GQ Threshold` is exactly the queue length, not whether if the lock is in use.

With that said, I have now added a new `Avoidance Mode`

 - `When Locked`
     If the semaphore is locked, it will output to pin 2
     
This gives you the control you need.
This should be available in the Node palette as **3.4.0**

![Screenshot 2024-05-24 at 07 40 09](https://github.com/marcus-j-davies/node-red-semaphore-plus/assets/55892693/912a4a99-6964-4351-99de-bf39d95dcde0)

**Comment by pshirshov** [comment]
Thank you very much.

Regarding the semantics - I understand your logic, though it's a bit odd that with GQ limit set to 0 all the messages would be rejected and with GQ limit set to 1 _two_ messages will be processed :)

**Comment by pshirshov** [comment]
Tested, works great, thanks again.
